---
apiVersion: v1
kind: Namespace
metadata:
  name: ews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gocurl
  name: gocurl
  namespace: ews
spec:
  progressDeadlineSeconds: 600
  replicas: 20
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: gocurl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        run: gocurl
    spec:
      containers:
      - image: rchench/gocurl:v0.0.4
        imagePullPolicy: IfNotPresent
        name: gocurl
        resources: {}
        securityContext:
          capabilities: {}
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /path
          name: myvol
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /path
          type: Directory
        name: myvol
---
apiVersion: v1
kind: Service
metadata:
  name: gocurl
  namespace: ews
  labels:
    app: gocurl
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
	targetPort: 8080
  selector:
    app: gocurl
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gocurl
  namespace: ews
spec:
  rules:
  - host: test.domain.com
    http:
      paths:
      - backend:
          serviceName: gocurl
          servicePort: 8080
        path: /gocurl
