---
- name: ubuntu upgrade
  hosts: all
  gather_facts: no
  remote_user: ubuntu

  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
